const data = {
    products:[
        {
            _id:'1',
            name:'Orange',
            category:'Fruit',
            image:'/images/OrangeImg.jpg',
            price: 120,
            brand: 'Orange',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name:'Orange',
            category:'Fruit',
            image:'/images/OrangeImg.jpg',
            price: 120,
            brand: 'Orange',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'3',
            name:'Orange',
            category:'Fruit',
            image:'/images/OrangeImg.jpg',
            price: 120,
            brand: 'Orange',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'4',
            name:'Orange',
            category:'Fruit',
            image:'/images/OrangeImg.jpg',
            price: 120,
            brand: 'Orange',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'5',
            name:'Orange',
            category:'Fruit',
            image:'/images/OrangeImg.jpg',
            price: 120,
            brand: 'Orange',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'6',
            name:'Orange',
            category:'Fruit',
            image:'/images/OrangeImg.jpg',
            price: 120,
            brand: 'Orange',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
    ]
}

export default data;